.TH ACXI 1 "2019\-07\-04" acxi "acxi manual"
.SH NAME
acxi  \- Command line audio conversion tool
.SH SYNOPSIS
\fBacxi\fR [\fB\-\-clean\fR] [\fB\-c\fR extensions] [\fB\-\-debug\fR] 
[\fB\-\-default\fR] [\fB\-d\fR destination-path] [\fB\-f\fR] [\fB\-h\fR] 
[\fB\-i\fR input-type] [\fB\-o\fR output-type] [\fB\-q\fR number] 
[\fB\-\-quiet\fR] [\fB\-s\fR source-path] [\fB\-V\fR] [\fB\-\-test\fR] 
[\fB\-v\fR]

.SH DESCRIPTION
\fBacxi\fR is a command line audio conversion program. It converts and syncs
all desired source lossless files to a lossy directory location. Supports 
lossless formats flac/wav/raw. Output formats are ogg, opus, or mp3.

By default, it will also copy over most common filetypes like gif, jpg, png, 
txt, pdf, doc, docx, and a few others. You can change the defaults using 
a configuration file.

The destination directory cannot be the same as the source directory, but
it can be inside of the source directory.

\fBacxi\fR runs pretests on each start to make sure input and output
directories exist, conversion programs for input and output formats 
exist on system, and conversion quality values are valid.

.SH USING OPTIONS

For example:
.B acxi
\fB\-o mp3\fR or \fBacxi \-fo opus\fR or \fBacxi \-d /home/you/music\fR

Note that some short form options have long form equivalents, which are
listed below. However, usually the short form is used in examples in order to
keep things simple.

.SH OPTIONS

.TP
.B \-\-clean\fR
Clean directories and files from destination (compressed) directories 
which are not present in the source music directories. Will show you the
directories or files to be removed before deleting them, and you have to
confirm the deletion of each set two times before it will actually delete
it. Runs before the syncing starts.

Take care with this one, if you have other compressed formats in your
compressed directory than your default $OUTPUT_TYPE format, it will 
want to delete all those, so do not use this option unless your compressed
directories are literal true copies of your source directories.

To confirm deletion of each group, you must first type 'delete' then
hit enter, then type 'yes' to confirm the deletion. This should avoid
errors and unintended deletions.

Note that this feature does not run in silent/quiet mode because it should
never be used automatically, or without explicit confirmation by the user.
It can be enabled using the CLEAN configuration option below so that 
acxi always cleans up before it starts syncing.

.TP
.B \-c [extensions]\fR,\fB \-\-copy [extensions]\fR
Comma separated list of extensions for file types you want to sync to your
lossy music directory. Overrides default values. Use lowercase, but it's
case insensitive internally. Do not include the period in the extension.

Default values are: bmp doc docx gif jpg jpeg odt pdf png tif txt

If you use no value, it will not copy anything.

Sample: \fB\-c txt,pdf,png,jpg,jpeg,gif\fR

.TP
.B \-\-debug\fR
Full screen output, including full verbosity of 
flac / oggenc / opusenc / lame conversion process for mp3, ogg, or 
opus output.

.TP
.B \-\-default\fR
Single line per operation screen output, default value for acxi.

.TP
.B \-d [path]\fR, \fB\-\-destination [path]\fR
Full path to the directory where you want the processed lossy
(eg, ogg) files to go.

.TP
.B \-f\fR, \fB\-\-force\fR
Overwrites all the mp3/ogg/opus/jpg/txt etc. files, even if they already 
exist. This is useful if you for example want to change compression
quality on existing files.

.TP
.B \-h\fR, \fB\-\-help\fR
This help menu.

.TP
.B \-i [flac|raw|wav]\fR, \fB\-\-input [flac|raw|wav]\fR
Input type. Supported types: flac, wav, raw. mp3 only supports flac input.

.TP
.B \-o [mp3|ogg|opus]\fR, \fB\-\-output [mp3|ogg|opus]\fR
Output type. Supported types: ogg, opus, mp3

.TP
.B \-q [number]\fR, \fB\-\-quality [number]\fR
For mp3: n can be an integer between 0\-9 (variable bit rate), 0 is 
largest file / highest quality.

For ogg: n can be between \-1 and 10. 10 is the largest file/highest quality. 
Fractions are allowed, e.g. \fB\-o ogg \-q 7.54\fR

For opus: n can be an integer between 6\-256 (bitrate). 256 is largest file/highest
quality.

Note that using a higher or lower quality than you used to create
the compressed files will not result in redoing those files unless 
you use the \fB\-f\fR / \fB\-\-force\fR option to force the overwrite 
of the existing files.

.TP
.B \-\-quiet\fR, \fB\-\-silent\fR
Turns off all screen output, except for error messages.

.TP
.B \-s [path]\fR, \fB\-\-source [path]\fR
Path to the top-most directory containing your source files (eg, flac).

.TP
.B \-\-test\fR
Test your configurations without actually doing the copy and sync 
operations. Activates \fB \-\-debug\fR as well for more complete output.
                  
.TP
.B  \-V\fR, \fB\-\-verbose\fR
Without full verbosity of debug, no flac/oggenc/opusenc/lame for mp3,
ogg, or opus conversion process screen output, but more verbose than
default.

.TP
.B \-v\fR, \fB\-\-version\fR
Show acxi version.

.SH CONFIGURATION FILE
acxi will read its configuration/initialization files in the
following order:

\fB/etc/acxi.conf\fR contains the default configurations. These can be 
overridden by user configurations found in one of the following locations.
 If \fB$XDG_CONFIG_HOME/acxi.conf\fR exists, it use it, else if
\fB$HOME/.conf/acxi.conf\fR exists, it will use it, and as a last default,
the legacy location \fB$HOME/.acxi.conf\fR is used, i.e.:

\fB$XDG_CONFIG_HOME/acxi.conf\fR > \fB$HOME/.conf/acxi.conf\fR >
\fB$HOME/.acxi.conf\fR

.SH CONFIGURATION OPTIONS

The following corresponds to the \fBBEGIN USER MODIFIABLE VALUES\fR section
in the top comment header of acxi.

.TP
.B APPLICATION PATHS

The following set your system path for the required applications:

\fBCOMMAND_FLAC\fR Sample: \fBCOMMAND_FLAC=/usr/bin/flac\fR (default path)

\fBCOMMAND_LAME\fR Sample: \fBCOMMAND_LAME=/usr/bin/lame\fR (default path)

\fBCOMMAND_METAFLAC\fR Sample: \fBCOMMAND_METAFLAC=/usr/bin/metaflac\fR 
(default path) Metaflac is required ONLY for flac to mp3, to copy over the 
ID3 tags If you are not going to make mp3s, only ogg or opus files for output, 
you do not need this

\fBCOMMAND_OGG\fR Sample: \fBCOMMAND_OGG=/usr/bin/oggenc\fR (default path)

\fBCOMMAND_OPUS\fR Sample: \fBCOMMAND_OPUS=/usr/bin/opusenc\fR (default path)

.TP
.B SOURCE/DESTINATION/CONFIGURATION DIRECTORIES

NOTE: DESTINATION_DIRECTORY cannot be the same as SOURCE_DIRECTORY.

\fBCLEAN\fR Sample: \fBCLEAN=true\fR Switches on/off \fB\-\-clean\fR to 
apply cleaning action to your destination directories. Accepted
values: \fB[enable|on|true|yes]\fR or \fB[disable|off|false|no]\fR. Default
is false.

\fBSOURCE_DIRECTORY\fR Sample: 

\fBSOURCE_DIRECTORY=/home/fred/music\fR 

This the original, working, like flac, wav, etc.

\fBDESTINATION_DIRECTORY\fR Sample: 

\fBDESTINATION_DIRECTORY=/home/fred/music/ogg\fR

This is the processed compressed music files, ie, ogg, opus, or mp3. Destination 
cannot be the same as Source directory, although it can be inside of the source 
directory.

NOTE: only use this if you are running Windows, or any OS without $HOME
or $XDG_CONFIG_HOME environmental variables. acxi will look for file:
acxi.conf inside that directory. You can see by running \fB\-h\fR
which will show paths being used to locate configuration files. 
CONFIG_DIRECTORY=/path/to/configuration/directory

.TP
.B INPUT/OUTPUT

The following are NOT case sensitive,ie flac/FLAC, txt/TXT will be 
found. INPUT_TYPE and OUTPUT_TYPE will be forced to lower case 
internally.

Changing quality levels will not redo existing files.

\fBINPUT_TYPE\fR Sample: \fBINPUT_TYPE=flac\fR 

\fBOUTPUT_TYPE\fR Sample: \fBOUTPUT_TYPE=mp3\fR 

\fBCOPY_TYPES\fR Sample: \fBCOPY_TYPES=doc,docx,bmp,jpg,jpeg\fR Use this
to override the default file types acxi will sync. Set to 'none', 
if you only want to sync the music files, not copy over images, text files,
etc.

\fBQUALITY_MP3\fR Sample: \fBQUALITY_MP3=2\fR Supported values: 0\-9. 0 is 
the largest file size / highest quality.

\fBQUALITY_OGG\fR Sample: \fBQUALITY_OGG=8.25q\fR Supported values: \-1 to 10. 
10 is the largest file size / highest quality. Supports fractions.

\fBQUALITY_OPUS\fR Sample: \fBQUALITY_OPUS=256\fR Supported values: 6\-256. 
256 is the largest file size / highest quality / best bitrate.

.TP
.B DEBUG OUTPUT
\fBLOG_LEVEL\fR Sample: \fBLOG_LEVEL=3\fR You can turn these to always on either
here or in config file by setting to desired verbosity level here directly,
or in the configuration file. 

0 \- quiet/silent \- no output at all (except for errors).

1 \- default \- single line per operation. This is the default, so you don't need 
to change it.
    
2 \- verbose \- but without the actual conversion data from codecs

3 \- debug \-  all available information.

.SH BUGS
Please report bugs using the following resources.

.TP
.B Issue Report
File an issue report:
.I https://github.com/smxi/acxi/issues
.TP
.B Forums
Post on acxi forums:
.I https://techpatterns.com/forums/about1491.html
.TP
.B IRC irc.oftc.net#smxi
You can also visit
.I irc.oftc.net
\fRchannel:\fI #smxi\fR to post issues.

.SH HOMEPAGE
.I  https://github.com/smxi/acxi

.SH  AUTHOR AND CONTRIBUTORS TO CODE

.B acxi
is a fork and full rewrite of flac2ogg.pl.

Copyright (c) Harald Hope, 2010\-2018

MP3 tagging: Odd Eivind Ebbesen \- \fIwww.oddware.net\fR \- 
<oddebb at gmail dot com>

Copyright (c) (flac2ogg.pl) 2004 \- Jason L. Buberel \- jason@buberel.org

Copyright (c) (flac2ogg.pl) 2007 \- Evan Boggs \- etboggs@indiana.edu

