.TH ACXI 1 "2023\-01\-23" acxi "acxi manual"
.SH NAME
acxi \- Command line audio conversion tool
.SH SYNOPSIS
Most of the commonly used options have short forms to make typing the commands
faster.
.IP * 2
Directories: [\fB\-\-destination\fR, \fB\-d\fR {destination-path}]
[\fB\-\-dot\fR] [\fB\-\-nlink\fR] [\fB\-\-no\-dot\fR] [\fB\-\-no\-nlink\fR]
[\fB\-\-recurse\fR {-1-xx}] [\fB\-\-source\fR, \fB\-s\fR {source\-path}] 
[\fB\-\-source\-glob\fR, \fB\-\-glob\fR, \fB\-g\fR {relative path}]
.IP * 2
Input/Output: [\fB\-\-input\fR, \fB\-i\fR {flac|raw|shn|wave}] 
[\fB\-\-output\fR, \fB\-d\fR {flac|mp3|ogg|opus}]
.IP * 2
Syncing:
[\fB\-\-append\fR, \fB\-\-copy\-append\fR, \fB\-a\fR {extensions}] 
[\fB\-\-clean\fR] [\fB\-\-codec\fR {aac|libfdk_aac2}] 
[\fB\-\-copy\fR, \fB\-c\fR {extensions}] [\fB\-\-copy\-append \fR {extensions}] 
[\fB\-\-dither\fR {dither\-type}]
[\fB\-\-exclude\fR, \fB\-x\fR {filename|extension}] 
[\fB\-\-exclude\-append\fR, \fB\-y\fR {filename|extension}] 
[\fB\-\-force\fR, \fB\-f\fR] [\fB\-\-fork\fR, \fB\-F\fR {0-xx}] 
[\fB\-\-quality\fR\fR, \fB\-q\fR {NUMBER}] 
[\fB\-\-resample\fR {bit-depth:sample-rate}]
.IP * 2
Tagging: [\fB\-\-autotag\fR, \fB\-A\fR] 
[\fB\-\-autotag\-create\fR, \fB\-C\fR] 
[\fB\-\-autotag\-create\-single\fR, \fB\-S\fR] 
[\fB\-\-autotag\-create\-multi\fR, \fB\-M\fR {filename start ID}]
[\fB\-\-autotag\-file\fR, \fB\-\-atf\fR, \fB\-\-af\fR, {file name}]
[\fB\-\-image\fR, \fB\-I\fR [cover image filename|remove]] 
[\fB\-\-info\-file\fR, \fB\-\-if\fR, \fB\-\-prefill\-file\fR, \fB\-\-pf\fR 
{release info file name}] 
[\fB\-\-infofix\fR, \fB\-X\fR [0acdklmnqtuvw]] 
[\fB\-\-info\-rating\fR {2\-xxx}
[\fB\-\-multiartist\fR, \fB\-\-ma\fR {[at|ta]:separator}]
[\fB\-\-prefill\fR, \fB\-E\fR] 
[\fB\-\-prefill\-tag\fR, \fB\-\-pt\fR {tags}] 
[\fB\-\-no\-replaygain\fR]
[\fB\-\-remove\-images\fR, \fB\-\-image\-remove\fR, \fB\-R\fR] 
[\fB\-\-remove\-padding\fR, \fB\-P\fR] 
[\fB\-\-start\fR {0-xx}] 
[\fB\-\-tag\fR, \fB\-T\fR] {"TAG1%:tag value^^TAG2%:tag value"}] 
[\fB\-\-taglist\fR, \fB\-L\fR [acfiw]] 
[\fB\-\-taglist\-file\fR {file name}] 
[\fB\-\-unique\fR {comma separated tags}] 
.IP * 2
Analyze/Checksums: [\fB\-\-analyze\fR, \fB\-Z\fR]
[\fB\-\-checksum\fR, \fB\-K\fR] [\fB\-\-checksum\-delete\fR, \fB\-D\fR] 
[\fB\-\-checksum\-ffps\fR, \fB\-\-ffps\fR] 
[\fB\-\-checksum\-verify\fR, \fB\-V\fR] 
[\fB\-\-duplicates\fR, \fB\-\-dupes\fR] [\fB\-\-ffprobe\fR]
[\fB\-\-infofix\fR, \fB\-X\fR [qv]] [\fB\-\-no\-ffp\fR] 
[\fB\-\-no\-md5\fR] 
[\fB\-\-z\-min\-size\fR {0\-xxx}] [\fB\-\-z\-min\-time\fR {0\-xxx}]
.IP * 2
Miscellaneous: [\fB\-\-aggregate\fR, \fB\-G\fR [file name|extension]]
[\fB\-\-config\fR, \fB\-\-configuration\fR]
[\fB\-\-help\fR, \fB\-h\fR] [\fB\-\-no\-ssl\fR] 
[\fB\-\-update\fR, \fB\-U\fR [3]] [\fB\-\-version\fR]
.IP * 2
Output Controls: [\fB\-\-verbosity\fR, \fB\-v\fR {0-3}] 
[\fB\-\-quiet\fR]
.IP * 2
Debugging: [\fB\-\-dbg\fR {1\-xx}[,y][,z]...]
[\fB\-\-dry\fR, \fB\-\-dry\-run\fR, \fB\-\-test\fR] 

.SH DESCRIPTION
\fBacxi\fR is a command line audio conversion program and audio processing 
program. It converts and syncs all desired source lossless files to the desired 
output format, and to a different directory location. 
.PP
Supports lossless input formats aiff/flac/raw/shn/wav. Output formats are flac, 
ogg, opus, aac/m4a, or mp3. aif/raw/shn can only output to flac. aac, m4a, mp3 
can only have flac as input format. Resampling can only have flac as input and
output formats.
.PP
By default, syncing will also copy over most common filetypes like gif, jpg, 
png, and txt. You can change the defaults using a configuration file, or using 
the \fB\-c\fR or \fB\-a\fR options.
.PP
The destination directory cannot be the same as the source directory, but it can 
be inside of the source directory.
.PP
It can also generate or verify md5 and ffp checksum files if required, as well 
as tag/embed images using \fBauto.tag\fR or \fB\-\-tag\fR / \fB\-\-image 
[filename]\fR methods.
.PP
\fBacxi\fR runs pretests on each start to make sure input and output directories 
are valid, conversion programs for input and output formatting programs are 
present, and other user values are correct.

.SH TABLE OF CONTENTS
This man page is pretty long and information packed. The options items are 
broken up into the same organization as the help menu. The man page is divided 
into the following sections:

* \fBDEPENDENCIES\fR Tools and codecs required by the various features.

* \fBUSING OPTIONS\fR How to use the command line options.

* \fBINPUT/OUTPUT OPTIONS\fR input, output codecs; source, destination 
directories; source globbing, dot files, recursion levels.

* \fBSYNCING OPTIONS\fR Options related to syncing your collection. Includes 
forking, clean, copy types, excludes, codecs, dither, quality, resample, 

* \fBTAGGING OPTIONS\fR Includes autotag, image embed, infofix, prefill, tag, 
tag list.

* \fBANALYZE/CHECKSUMS OPTIONS\fR Analyze, duplicates, checksums.

* \fBMISCELLANEOUS OPTIONS\fR Aggregate files, help, version, self\-updater.

* \fBDEBUG/OUTPUT CONTROL OPTIONS\fR Dry run, debug, verbosity levels.

* \fBCONFIGURATION FILE\fR Configuration file name, locations, and configuration 
values. 

* \fBBUGS\fR Where to report bugs, or make issue requests etc. 

* \fBHOME PAGE/AUTHORS\fR Home page, copyright, authors, etc.

.SH DEPENDENCIES
For backward compatibility, acxi requires only Perl 5.010 (or newer), so it 
should run on anything. Several features (copy, make directory, find files) were 
moved from *nix commands to Perl native commands in version 3, which should make 
acxi fully platform agnostic.
.IP * 2
\fBAAC/M4A\fR encoding requires \fBffmpeg\fR with either \fBlibfdk_aac\fR 
(Debian/Ubuntu package: \fBlibfdk_aac2\fR) or native \fBffmpeg aac\fR codec. 
Source file must be flac. To transfer tags, \fBm4a\fR must be used.
.IP * 2
\fBFLAC\fR resampling requires \fBffmpeg\fR and \fBmetaflac\fR (for source file 
sample rate data).
.IP * 2
\fBMP3\fR encoding requires: \fBlame\fR and \fBflac\fR. Source file must be 
flac. MP3 encoding does not support wav or raw input formats.
.IP * 2
\fBOgg\fR encoding requires \fBoggenc\fR (Debian/Ubuntu package: 
\fBvorbis-tools\fR).
.IP * 2
\fBOpus\fR encoding requires \fBopusenc\fR (Debian/Ubuntu package: 
\fBopus-tools\fR).
.IP * 2
\fBSHN \-> \fBFLAC\fR conversion requires the codec \fBshorten\fR and 
\fBffmpeg\fR.
.IP * 2
\fB\-\-analyze\fR, \fB\-\-duplicates\fR, \fB\-\-ffps\fR, and \fB\-\-infofix 
[qv]\fR require \fBmetaflac\fR (with the following exception).
.IP * 2
\fB\-\-analyze\fR, \fB\-\-infofix q\fR require \fBffprobe\fR for non \fBflac \fR 
input types, or if using \fB\-\-ffprobe\fR option with input type \fBflac\fR.
.IP * 2
\fB\-\-autotag\fR, \fB\-\-tag\fR, \fB\-\-image\fR, and \fB\-\-image\-remove\fR 
require \fBmetaflac\fR for \fBVORBIS\fR tagging.
.IP * 2
\fB\-\-checksum\fR and \fB\-\-checksum\-delete\fR require \fBmetaflac\fR and 
\fBmd5sum\fR (or any comparable program that generates md5sums). 
.IP * 2
\fB\-\-checksum\-verify\fR and \fB\-\-infofix v\fR require the \fBflac\fR 
executable.
.IP * 2
\fB\-\-checksum\-verify\fR requires \fBmd5sum\fR (or any comparable program that 
generates md5 hashes). 
.IP * 2
\fB\-\-fork\fR requires Perl module \fBParallel::ForkManager\fR.
.IP * 2
\fB\-\-infofix c\fR requires Perl Core Module \fBEncoding::Guess\fR. 
.IP * 2
\fB\-\-infofix k\fR requires Perl Core Module \fBPOSIX::strftime\fR. 
.IP * 2
\fB\-\-infofix [tu]\fR require Perl module \fBText::Autoformat\fR. 
.IP * 2
\fB\-\-taglist\fR require \fBmetaflac\fR for getting \fBFLAC\fR tags.
.IP * 2
\fB\-U\fR Self-updater requires \fBcurl\fR. 
.PP
In theory, acxi 3.x should run on Windows and Macs, but I have not tested that, 
but as long as the source/destination directory paths and the 
application/configuration paths are correct, it should 'just work'.

.SH USING OPTIONS
For example:
.EX
\fBacxi \-o mp3\fR or \fBacxi \-fo opus\fR or \fBacxi \-d /home/you/music\fR
.EE
.PP
Note that some options have long and short forms. The short form is used when 
available in examples in order to keep things simple.
.PP
All tagging or checksum options (\fB\-A\fR, \fB\-C\fR, \fB\-\-dupes\fR, 
\fB\-D\fR, \fB\-E\fR, \fB\-\-ffps\fR, \fB\-G\fR, \fB\-I\fR, \fB\-K\fR, 
\fB\-M\fR, \fB\-P\fR, \fB\-R\fR, \fB\-S\fR, \fB\-T\fR, \fB\-V\fR, \fB\-Z\fR) 
must have an explicit source (\fB\-s\fR) location supplied to avoid errors.

.SH INPUT/OUTPUT OPTIONS
These options are related to input/output actions, and may apply to sync, 
analyze, checksum, tagging, and aggregate options.

.TP
.B \-\-destination, \fB\-d {path}\fR
Full path to the directory where you want the processed lossy (eg, ogg) files to 
go. Cannot start with \fB../\fR.

.TP
.B \-\-dot\fR
Disables the default behavior when creating file/directory syncing/action lists 
of excluding dot files and directories (like \fB/home/user/.config\fR). Added by 
request, but use at your own risk, I take NO responsibility for any unintended 
consequences. Note that if you do find unintended consequences, you should be 
able to filter those out using additional \fB\-\-exclude\fR lists.

.TP
.B \-\-glob\fR, \fB\-g\fR, \fB\-\-source\-glob {path relative to \-s path}\fR
.br
See \fB\-\-source\-glob\fR.

.TP
.B \-\-input\fR, \fB\-i {aif|flac|raw|shn|wav}\fR
Input type. Supported types: flac, wav, raw, shn. 

\fBaif\fR/\fBraw\fR/\fBshn\fR/\fBwav\fR \- only support flac output. 

\fBshn\fR \- requires the shorten codec, which you usually have to build 
yourself unless you can find a package for it. Use \fB\-v 3\fR to test the 
first time to make sure you have shorten codec installed.

Some other input types may be active for testing purposes occasionally, but acxi 
does not promote, advocate, or officially support those types (like mp3 to 
flac). 

Supports flac to flac for cases where you might want to redo flac files to known 
quality/compression levels, or redo them using current flac codecs.

Tags transfer from AIF files that are tagged to FLAC files in my tests.

.TP
.B \-\-nlink\fR
Set \fB$File::Find::dont_use_nlink = 0\fR. Default is \fB1\fR. Only change this 
if you have a reason to do so. Setting value to \fB0\fR may make \fBcifs\fR type 
file system reads fail, on a \fBsamba\fR network share for example. If you 
encounter issues with the default value, please post an issue on the acxi github 
page.

See this PerlMonks thread for an explanation: 
\fIhttps://www.perlmonks.org/?node_id=1180606\fR

.TP
.B \-\-no\-dot\fR
Overrides user configuration \fBDOT\fR. Basically restores default behavior for 
acxi in terms of skipping all dot files. Only useful if you have set \fBDOT\fR 
to true in your configuration file and want to do a one time override of that 
setting.

.TP
.B \-\-no\-nlink\fR
Set \fB$File::Find::dont_use_nlink = 1\fR. This is the default value. See 
\fB\-\-nlink\fR for details.

.TP
.B \-\-output\fR, \fB\-o {aac|flac|m4a|mp3|ogg|opus}\fR
Output type. Output only for syncing operations. Supported types: aac, flac, 
ogg, opus, m4a, mp3

\fBaac\fR \- only supports flac input type, To preserve flac tags, use m4a.

\fBflac\fR \- only supports aiff, flac, shn, wav, or raw input types.

\fBm4a\fR \- only supports flac input type, Container around aac data. Use if 
you want to preserve flac tags in your aac audio file.

\fBmp3\fR/\fBogg\fR/\fBopus\fR \- only support flac input type.

.TP
.B \-\-recurse {number}\fR
There may be cases where you want a certain action to NOT recurse beyond the 
number of steps you supply as an argument for this option. Default recursion 
level is infinite (-1). If you use 0, it will only return files for the current 
directory.

This can be useful if you for example do not want to create ffp or md5, or sync 
files in a sub directory.

In general, use the \fB\-\-test\fR option to verify the results are what you 
expected before actually proceeding with this option for real.

.TP
.B \-\-source\fR, \fB\-s {path}\fR
Path to the top-most directory containing your source files (eg, flac). Cannot 
start with \fB../\fR.

.TP
.B \-\-source\-glob\fR, \fB\-\-glob\fR, \fB\-g {path relative to \-s path}\fR
Accepts wild card paths if you only want to update or check certain directories 
within the main \fB\-\-source\fR working directory. Requires \fB\-\-source\fR 
(or pre-configured \fBSOURCE_DIRECTORY\fR), wild card path must be within 
\fB-\-source\fR.

Sample:
.nf
\fBacxi -s ./ \-g 'BandName*' \-V
acxi -s ./ \-g '{BandName,Band Name,Band_Name}*' \-V\fR
.fi

Will only verify folders tarting with BandName. Remember to always quote the 
value otherwise your shell will expand the wild cards!!

Uses standard globbing patterns: * one or more of anything; {one,two,three} 
matches one of the comma separated values inside {...}. Note that * only matches 
directory names or files, not the path separator, like /.

Works with all options except \fB\-\-clean\fR and \fB\-\-prefill\fR.

.SH SYNCING OPTIONS
Sync your lossless collection to lossy, or to another lossless format, or 
resample lossless to lossless.
.TP
.B \-\-append\fR, \fB\-\-copy\-append\fR, \fB\-a {extensions}\fR
Takes one or more comma separated extensions. Do not use whitespaces in this 
list. These will be appended on to the current list being used on a one time 
basis. This can be useful if you want to copy over a specific file type for one 
sync action without having to make a full list with \fB\-c\fR.

Sample: \fBacxi \-a tag,md5\fR will add md5 and tag file type to copy list.

.TP
.B \-\-clean [sync]\fR
Clean directories and files from destination (compressed) directories which are 
not present in the source music directories. Will show you the directories or 
files to be removed before deleting them, and you have to confirm the deletion 
of each set two times before it will actually delete it. If used with optional 
value \fBsync\fR, will proceed to sync actions, otherwise exits after cleaning.

The paths provided by \fB\-s\fR and \fB\-d\fR must be relative to either root or 
\fB$HOME\fR:
.EX
\fBacxi \-\-clean \-s /home/fred/music \-d /home/fred/music/opus\fR
.EE
OR
.EX
\fBacxi \-\-clean \-s ~/music \-d ~/music/opus\fR
.EE

Take care with this one, if you have other compressed formats in your compressed 
directory than your default $OUTPUT_TYPE format, it will want to delete all 
those, so do not use this option unless your compressed directories are literal 
true copies of your source directories.

To confirm deletion of each group, you must first type 'delete' then hit enter, 
then type 'yes' to confirm the deletion. This should avoid errors and unintended 
deletions.

Note that this feature does not run in silent/quiet mode because it should never 
be used automatically, or without explicit confirmation by the user. It can be 
enabled using the CLEAN configuration option below so that acxi always cleans up 
before it starts syncing.

.TP
.B \-\-codec {libfdk_aac|aac}\fR
Currently only supported for aac/m4a output using ffmpeg.

.TP
.B \-\-copy\fR, \fB\-c {extensions}\fR
Comma separated list of extensions for file types you want to sync to your lossy 
music directory. Overrides default values. Use lowercase, but it's case 
insensitive internally. Do not include the period in the extension.

Default values are: bmp doc docx gif jpg jpeg odt pdf png tif txt

If you use no value, it will not copy anything.

Sample: \fB\-c txt,pdf,png,jpg,jpeg,gif\fR

.TP
.B \-\-dither {dither-type}\fR
Use with \fB\-\-resample\fR and if you want to use a different dither type than 
default shibata. Possible values:
.nf
\fB0\fR \- no dither
\fBrectangular\fR \- rectangular dither
\fBtriangular\fR \- triangular dither
\fBtriangular_hp\fR \- triangular dither with high pass 
\fBlipshitz\fR \- Lipshitz noise shaping dither
\fBshibata\fR \- Shibata noise shaping dither (default value)
\fBlow_shibata\fR \- low Shibata noise shaping dither
\fBhigh_shibata\fR \-  high Shibata noise shaping dither
\fBf_weighted\fR \- f-weighted noise shaping dither
\fBmodified_e_weighted\fR \- modified-e-weighted noise shaping dither
\fBimproved_e_weighted\fR \- improved-e-weighted noise shaping dither
.fi

Read more on these dither types here: 
\fIhttps://ffmpeg.org/ffmpeg-resampler.html\fR

Dithering is only applied if being resampled to sample depth of less than 24 
bit.

.TP
.B \-\-exclude\fR, \fB\-x {items}\fR
Exclude a list of unique strings separated by ^^, or a full path to an exclude 
file whose name includes the value set in \fB$EXCLUDE_BASE\fR. 

Excludes sync/copy action to destination directory. Replaces \fBEXCLUDE\fR 
values if present. Anything matching in any part of the source directory file 
path will be excluded or removed from the destination directory. 

If it's a path to a file of excludes, use one exclude string per line.

Samples:
.nf
\fB\-\-exclude='artwork^^Daisy Queen^^Bon Jovi'
\-\-exclude='/home/me/music/excludes/acxi-excludes-phone.txt\fR
.fi

If you want to temporarily suspend exclude actions one time, use: 
\fB\-\-exclude='UNSET'\fR

.TP
.B \-\-exclude\-append\fR, \fB\-y {items}\fR
Append an item to the list of excludes or file. Only accepts string values, not 
a file path.

Sample: \fB\-\-exclude\-append='My Sharona^^Dancing Queen'\fR

.TP
.B \-\-ffprobe\fR
Force \fB\-\-analyze\fR and \fB\-\-infofix q\fR to use ffprobe instead of 
metaflac for flac files. Useless!!! Incredibly slow, but just in case you want 
to confirm the outputs of the two, or something. My tests showed 30x slower.

.TP
.B \-\-force\fR, \fB\-f\fR
Overwrites all the mp3/ogg/opus/jpg/txt etc. files, even if they already exist. 
This is useful if you for example want to change compression quality on existing 
files.

.TP
.B \-\-fork\fR, \fB\-F {0-xx}\fR
Uses Perl module \fBParallel::ForkManager\fR to allow for forking of audio file 
conversions actions. This can speed up your syncing a lot depending on how many 
threads your CPU can support and how many you assign with this option.

Supports integer values \fB0\fR or greater, but tests show 1 is slower than not 
using forking at all. \fB0\fR is default, and disables forking.

Some debugging features will be slightly distorted if fork is used, but it is 
only cosmetic.

See also configuration file option \fBFORK\fR if you want to set this 
permanently.

Please note that this can have strange consequences if you run it on a huge job, 
even if you use only half your threads, the system can still act strange as a 
result of running it with multiple forks.

.TP
.B \-\-quality\fR, \fB\-q {number}\fR
Set compression quality level.

\fBaac/m4a\fR \- n can be an integer between 10\-500 (bitrate). 500 is largest 
file/highest quality.

\fBflac\fR \- n can be an integer between 0\-8, 0 is largest file / fastest 
conversion time, 8 is smallest file, longest time. Note that tests show there is 
very little point in using anything over 4.

\fBmp3\fR \- n can be an integer between 0\-9 (variable bit rate), 0 is largest 
file / highest quality.

\fBogg\fR \- n can be between \-1 and 10. 10 is the largest file/highest 
quality. Fractions are allowed, e.g. \fB\-o ogg \-q 7.54\fR

\fBopus\fR \- n can be an integer between 6\-256 (bitrate). 256 is largest 
file/highest quality.

Note that using a higher or lower quality than you used to create the compressed 
files will not result in redoing those files unless you use the \fB\-f\fR / 
\fB\-\-force\fR option to force the overwrite of the existing files.

.TP
.B \-\-resample {bit depth:sample rate khz}\fR
Allows for standard resampling options: 16|20|24 bit depth and 
44.1|48|88.2|96|192 khz sampling rate. 

To get best results, always make sure to resample to a sampling rate that 
divides evenly into the original sampling rate, for example, if the original is 
96khz sampling rate, 24 bit, resample to 48khz, 16 bit (96/2 == 48). 

If you use values that do not divide evenly, you have to deal with synthesizing 
sample issues (depending on how the resampling is done, of course), and your 
audio will not be as good as it could be. Note that 44.1 is only required for 
Audio CDs, and in most cases, the cd burning software can deal with that itself, 
unless you want to force it using acxi.

In short, if you have 192 or 96 khz originals, resample them to 48 khz. If you 
have 88.2 khz, resample it to 44.1. Do not sample upwards, it's just wasted 
bytes, for example, there is no reason to resample from 44.1 to 88.2. In almost 
all cases, if you need to work like that, use a dedicated DAW program like 
Audacity and let it do the resamplings to higher levels in its native mode, then 
after you have worked on the project, save it, and export to normal sampling 
rates and bit depths.

IMPORTANT: use the \fB\-Z\fR analyze option first to make sure what the bit 
depth and sampling rate of your files are before using this resampling option. 
\fB\-\-resample\fR and \fB\-\-analyze\fR are meant to be used together to avoid 
errors, and so you always can be sure of what you are actually dealing with.

Output for \fB\-v1\fR shows source file bit-depth:sample-rate and resample 
bit-depth:sample-rate per file. \fB\-v2\fR adds dither type to output resample 
data. Dither (\fBshibata\fR default, use \fB\-\-dither {type}\fR for alternates) 
is added when sampling from bit depths of 24 or more to less than 24.

Sample:
.nf
\fB# to get sampling rates etc:
acxi \-s ./ \-Z
[.... output...]
# then run resampling once you have determined sampling rates etc
acxi \-s working \-d results \-i flac \-o flac \-\-resample 16:48\fR
.fi

.TP
.B \-\-resample\-override\fR
Allows users to select any supported bit depth (4\-32) and sample rate, in khz 
(1\-655). Why you would want to do this is beyond me, but if you want to, you 
can if you add this override switch.

.SH TAGGING OPTIONS
Create autotag files, fix info files, create prefills, image embedding and 
removal, command line and autotag tagging.
.TP
.B \-\-autotag\fR, \fB\-A\fR
Requires specially formatted file, default name \fBauto.tag\fR, to be put into 
each music collection directory. See the file for explanations.

FLAC input files only. OGG/Opus may be added. Will search source directory for 
\fBauto.tag\fR and update each collection/album that has that file present with 
the tagging information contained in it.

Note that all existing tags are removed. Default is to preserve the existing 
\fBREPLAYGAIN\fR tags in the \fBauto.tag\fR file since the assumption is those 
were generated for a reason.

See github acxi page for a blank sample file, but make sure to use 
\fB\-\-autotag\-create\fR, \fB\-\-autotag\-create\-single\fR, or 
\fB\-\-autotag\-create\-multi [prefix]\fR because it's a LOT faster that way, 
and you don't have to find the file. These file builders also preserve existing 
\fBREPLAYGAIN\fR and \fBWAVEFORMATEXTENSIBLE_CHANNEL_MASK\fR data found in the 
track file.

Notes on \fBIMAGE\fR: Avoid using large images, and as far as I can tell, 
there's no point in using anything other than the standard 'cover' type image 
(type 3). Keep sizes down by optimizing the image down to around 30\-60 KiB, 
300\-400 pixel width. 

If you make a mistake, or want to undo the images, use \fB\-\-remove\-images 
\-\-autotag\fR after updating the \fBauto.tag\fR file by either removing the 
value for \fBIMAGE\fR or changing the value. Most media players I tested on only 
pay attention to the main image, and only one of them. Don't use a flac file as 
a way to store large high resolution images as a general rule, it just makes the 
entire collection pointlessly bloated.

Can be used with \fB\-K\fR or \fB\-D\fR for all in one tag checksum actions.

See \fB\-\-tag\fR or \fB\-\-image\fR for updating/modifying existing FLAC 
comment values, or adding images to your FLAC files.

.TP
.B \-\-autotag\-create\fR, \fB\-C\fR
Creates the \fBauto.tag\fR file in the directory, and populates it with field 
names, and per track blocks that include the track file name so you can just 
fill out the fields you want. Not recommended.

if you use the \fB\-\-autotag\-create\-single\fR or 
\fB\-\-autotag\-create\-multi\fR options instead Will also populate the 
\fBTRACKNUMBER\fR and \fBTRACKTOTAL\fR fields.

All existing \fBREPLAYGAIN\fR tags for the audio files are preserved and used in 
the auto.tag file. If want to remove those, use the \fB\-\-no\-replaygain\fR 
option. 

.TP
.B \-\-autotag\-create\-multi\fR, \fB\-M {file prefix}\fR
Similar to \fBautotag\-create\-single\fR except it includes a prefix argument 
which is the unique per disk track file name ID. Uses \fB%\fR to indicate a 
number between 1 and 9, or \fB@\fR to indicate an upper/lower case letter from A 
to Z. 

Use together with \fB\-E\fR (\fB\-\-prefill\fR) To prepopulate the \fBALBUM,\fR 
\fBARTIST\fR, \fBALBUMARTIST\fR, \fBPERFORMER\fR, \fBDATE\fR, \fBYEAR\fR, and 
\fBTITLE\fR fields as well. 

Samples: 
\fB\-M d%\fR [d1track02.flac]; \fB\-M d%\-\fR [d2\-track04.flac];
\fB\-M %\fR [112.flac]; \fB-M 2015-03-21.d%.\fR [2015-03-21.d1.track03.flac]

\fB\-M d@\-\fR [dAtrack02.flac]; \fB\-M d@\-\fR [dB\-track04.flac];\n";
\fB\-M @\fR [a12.flac]; \fB-M 2015-03-21.d@.\fR [2015-03-21.da.track03.flac]

This will create prepopulated \fBDISCTOTAL\fR, per disk 
\fBDISCNUMBER\fR and \fBTRACKTOTAL\fR, and per track \fBTRACKNUMBER\fR fields. 
This saves a lot of time when tagging multi disk sets.

Caveat: does not work with per disk subfolders, sorry.

.TP
.B \-\-autotag\-create\-single\fR, \fB\-S\fR
When creating \fBauto.tag\fR file, as well as populating the per track file 
names, it also fills in the \fBTRACKTOTAL\fR and \fBTRACKNUMBER\fR fields.

Do not use for multidisk recordings since the totals per disk and the track 
numbering for the second or more disks will be wrong, but for single disks, it 
will speed up slightly the time required to manually populate the \fBauto.tag\fR 
file.

Use together with \fB\-E\fR (\fB\-\-prefill\fR) To prepopulate the \fBALBUM,\fR 
\fBARTIST\fR, \fBALBUMARTIST\fR, \fBPERFORMER\fR, \fBDATE\fR, \fBYEAR\fR, and 
\fBTITLE\fR fields as well.

.TP
.B \-\-autotag\-file\fR, \fB\-\-atf\fR, \fB\-\-af\fR {file}
An alternate file name to use for auto.tag file. Note that file MUST have a 
*.tag extension, and should not be anything other than ASCII or UTF8, otherwise 
you will get ungood results.

.TP
.B \-\-image\fR, \fB\-I [cover image file name|remove]\fR
Flac only. Use only on a single directory. Takes the supplied cover image file 
and embeds it into the existing flac files. Only use \fB.png\fR or \fB.jpg\fR 
image types, otherwise the results may be inconsistent. 

Do not use if you are using an \fBauto.tag\fR file, this is is intended only to 
add an image to an already tagged .flac file without retagging it, or to remove
images from those files, or to replace old images with the supplied file name.

The value \fBremove\fR removes all embedded images and their padding. \fB\-RI\fR 
can be used as shorthand for \fB\-Iremove\fR or \fB\-I[image] 
\-\-remove\-images\fR. If remove is not used, -I will not add new images to the 
file if pre-existing images are found in it (image embedding is cumulative in 
FLAC files). 

Only run this in a single recording directory, do not use globally!!

Samples:
.nf
\fBacxi \-s ./ \-\-image='cover.jpg'
acxi \-s ./ \-\-image remove
acxi \-s ./ \-I cover.jpg \-\-remove\-images
acxi \-s ./ \-RI cover.jpg
acxi \-s ./ \-RI
.fi

.TP
.B \-\-info\-file\fR, \fB\-\-if\fR, \fB\-\-prefill\-file\fR, \fB\-\-pf\fR {file}
An alternate file name to use for prefill or infofix. Note that file MUST have a 
*.txt extension, and should not be anything other than ASCII or UTF8, otherwise 
you will get ungood results.

.TP
.B \-\-infofix\fR, \fB\-X [0acdklnqtuvwz]\fR
Correct common corruptions to info.txt files. Note that this can be used in bulk 
mode on sets of directories if all the info text files have the same name.

You can use any combination of the following options, or no options.

* no option \- clean white space. Trim white spaces off line ends, get rid of 
extra new lines, convert multiple white spaces to single space. Also change tabs 
to space. This always runs.

* \fB0\fR \- (zero) turn off leading characters per info file. Useful if you 
want to use output for copy/paste actions etc.

* \fBa\fR \- In cases where track or setlist is not numbered, add numbering 
using start code \fB:an:\fR or \fB:an-[number]:\fR. Terminates using same 
terminators as n m t.

Will skip empty lines and things like Setlist:, Tracks:, Tracklist:, Disk 1:, 
Set 1:, Encore:, and of course, itself. The :an..: must be the only thing on its 
line.

This makes the tedious process of adding track numbers a lot faster. For 
multidisk or set releases, use the \fB:an-1:\fR, \fB:an-2:\fR, and so on, to 
indicate that the following track numbers should start at 1, and reset to 1 
every new \fB:an-[number]:\fR found.

.nf
:an: changes 
\fB:an:
Song Title\fR
to
\fB01. Song Title\fR
and :an-[number]: changes:
\fB:an-1:
Disk 1:
Song Title
 ...
:an-2:
Disk 2:
Song Title\fR
to
\fBDisk 1:
1-01. Song Title
 ...
Disk 2:
2-01. Song Title\fR
.fi

Make sure to add the colon after Setlist, Tracks, Disc 1, Set 1, Encore, etc or 
they will be treated as track titles. And make sure to terminate the tracklist 
with a terminator or every following line will be numbered.

Note that once you write changes, the :an item will be removed automatically 
from the info file.

* \fBc\fR \- Try to change CP\-1252 Windows special characters like magic quotes 
to clean ASCII equivalents. Should handle most, but if it hits one it does not 
know about, it will let you know with a message. To let you find these in 
collections (do NOT bulk write since you should always verify fixes as correct 
per file!), search the output for:

\fBacxi \-s./ \-X0c | grep \-E 'Processing:|CF:|Encoding:'\fR

That will show you all directories with bad characters, what encoding type was 
discovered, and if CP\-1252, if they are correctible or not. There may be other 
character sets this does not handle, but this should cover most common cases, 
since most of these come from MS Word, notepad, or similar Windows generated 
*.txt files. 

Be careful with this one, the tests are not completely reliable, so check before 
writing changes to file. It does not try to map European characters to ASCII, so 
you have to fix those yourself. Recommend changing document to UTF 8 after the 
special characters have been fixed, then correcting the European characters.

Note that this is only able to test for UTF8, CP\-1252, and ASCII. Other 
character sets are too difficult to handle. If it found, or failed to find, the 
encoding, it will show that in a message. An Encoding showing as ending with 
\fB\-2\fR means it used a fallback detection.

For character encoding issues, the perfect is the fatal enemy of the good. 
Detection results for valid CP\-1252 and ASCII encodings are so far quite 
reliable, UTF8 a bit less so.

* \fBd\fR \- set date to ISO format YYYY\-MM\-DD. Use this to correct dates that 
are non ISO YYYY\-MM\-DD, like May 23, 1983; 4/12/78; 2011-8-12; 18.4.21. Always 
double check file to make sure they aren't using some really silly date format, 
and confirm with d option before using wd to make sure it is as expected. 
Pretests for less common formats like dd/mm/yyyy by checking for a day/month > 
13 in first or second position anywhere in the file.

* \fBk\fR \- set date to ISO format and add day of week after date. Also removes 
any existing day of weeks from that line. Only does this on first date found in
info file, which should be on top block.

Sample: \fBThursday, April 23, 2020\fR becomes \fb2020-04-23 (Thursday)\fR

* \fBl\fR \- more simplistic upper case first, lower case rest. Good for info 
files that have all upper case, but a lot of sentences. You will have to go back 
in and correct items. Good in combination with \fBt\fR.

* \fBm\fR \- add (..) around track time when it's included in track title at end 
of Title string. Required for the prefill track title cleanup of track times. If
time is located at start of track title, after disk/track numbers, moves to end.
Note that \fBm\fR should be used together with \fBn\fR for best results. 

* \fBn\fR \- fix track numbering to be consistent '0X. ' or 'Y-0X'. See 
\fB\-\-prefill\fR track terminators for stopping fixes at end of track listing. 
Use when track numbering is defective or inconsistent. 

* \fBq\fR \- add in technical quality info lines after top header. Reads flac 
file in directory to determine bit rate, sampling frequency, and channels. 
Requires track file name starts with D-NN or ends with D-NN.flac. Exits if it 
can't find a match. Quality is /[rating] number and can be changed from default 
if desired.
.nf
\fBFLAC: 16/44.1 (2 channels)
Quality: /4 ()
Time: 29:35.01
Size: 324.2 MiB
Average kb/s: 768
Tracks: 7\fR
.fi

* \fBt\fR \- smart upper case first track titles only. Requires Perl module 
\fBText::Autoformat\fR. See \fB\-\-prefill\fR track terminators for stopping at 
end of track listing.

* \fBu\fR \- run upper case first smart fix. Requires Perl module 
\fBText::Autoformat\fR. Use this if entire file is uppercase (this happens 
surprisingly often). Applies smart Autoformat fix (\fBu\fR) for Upper/lower 
case, not recommended if the file has a lot of text in it. Perfect for titles 
and most standard values, but not for paragraghs of text.

* \fBv\fR \- validate \fBFFP\fR hash signatures. \fBFLAC\fR only. Activates 
\fBq\fR. Adds \fBFLAC FFPs:\fR status line to the \fBq\fR report.

* \fBw\fR \- write changes to info file.

With no \fBw\fR supplied, will just show what would have happened, with \fBw\fR, 
writes fixes to file.

Info file fixes would be used before running \fB\-E\fR, and not with any other 
option. 

See \fB\-\-info\-file\fR for using alternate info txt file names.

Samples: \fBacxi \-s./ -X dtn\fR (to test) \fBacxi \-s./ -X dtnw\fR (to apply)

.TP
.B \-\-info\-rating {2\-xxx}\fR
Any number greater than 1 for the \fB\-\-infofix q\fR item \fBQuality: /[rating 
number]\fR line if you want to change from default of 4. Some people like rating 
by x/100, others x/10, etc. Use with \fB\-X q\fR or set in configurations.

.TP
.B \-\-multiartist\fR, \fB\-\-ma\fR {[at|ta]:separator}\fR
Use with \fB\-\-prefill\fR if the recording is multiartist, and the source info 
file is in Artist [separator] Title or Title [separator] Artist format. Note 
that all track titles must be in the same format, and the first item before the 
separator cannot contain the separator. There must be 1 or more spaces before 
and after the [sep] value in the info track string.

* \fBat\fR \- Artist [sep] Title
.br
* \fBta\fR \- Title [sep] Artist

Only include the actual non space character(s) used to separate the two items.

.nf
Example (info file track title format: 23. Band Name / Song):
\fBacxi \-s ./ \-SE \-\-ma 'at:/'\fR
Example (info file track title format: 23. Band Name - Song-Name):
\fBacxi \-s ./ \-SE \-\-ma 'at:-'\fR
Example  (info file track title format: 22. Song \\ Band Name):
\fBacxi \-s ./ \-SE \-\-ma 'ta:\\'\fR
Example (info file track title format: 03. Song \\\\ Band Name):
\fBacxi \-s ./ \-SE \-\-ma 'ta:\\\\'\fR
.fi

Not OK (info file track title format: 23. Band \- Name - Song). This would result 
in the following:
.br
Artist: \fBBand\fR
.br
Title: \fBName - Song\fR

If you have such a conflict, simply change separators in the info file to 
a character that does not occur in the first item.

However, this format: \fB23. Band\-Name - Song\fR works fine, since there are no 
spaces around the first \-.

You must use single quotes around the argument or things like backslashes may 
behave oddly. Do not include whitespaces in the separator value. The separator
itself cannot contain a whitespace.

If the match fails for some reason, \fBacxi\fR will exit with error message 
telling you which track title and separator failed. It will often be because 
there was a space missing on one or both sides of the separator.

.TP
.B \-\-no\-replaygain\fR
Remove any existing \fBREPLAYGAIN\fR and \fBWAVEFORMATEXTENSIBLE_CHANNEL_MASK\fR 
tags when creating a new \fBauto.tag\fR file. See \fB\-\-autotag\-create\fR for 
details.

.TP
.B \-\-prefill\fR, \fB\-E\fR
Will attempt to populate \fBauto.tag\fR file using data from \fBinfo.txt\fR file 
located in flac directory. 

Two distinct methods are used for Artist, Venue, Location, and Date 
pre\-filling. 

No blank lines or unsupported data can be in top block for either pre\-fill 
method. 

.B Automatic Detection of Fields

Automatic detection requires that the data must have an extremely specific 
syntax for this type of prefill to work:

* Band/Artist name must be first line in file. 

* Date must be iso \fBYYYY\-MM\-DD\fR formatted, and must be the first thing on 
its line, and must be in first 6 lines of file. See \fB\-Xd\fR to apply date 
fixes. \fBYEAR\fR is generated from Date.

* Location can be 1 or more lines not starting with \fB19|20XX\fR on lines 2-6. 
Each non\-date item will be added one by one until it reaches the end of the 
block, so make sure the block is in the order you want, or, better, use the 
explicit field name method.

.B Using Existing Field Names

Alternately, if the first line contains a supported field name folowed by a ':', 
pre\-fill will switch to using field names to match to tag names. Note that the 
field names are not case sensitive. This method is much more reliable than 
auto\-detection.

All field names must be followed by a ':'. Space before/after ':' optional, and 
ignored. The value after the colon will be used as the tag value.

If a field name should be added, just let us know what it is and we'll add it.

Supported field names, and their corresponding tag name (note: all two word 
field names can use a space, \fB\-\fR, \fB_\fR or no space as word separators):

.nf
\fBALBUM\fR \- Album.
\fBALBUMARTIST\fR \- AlbumArtist, Album Artist.
\fBALBUMSORT\fR \- AlbumSort, Album Sort.
\fBARTIST\fR \- Artist, Artists, Artiste, Artistes, Band, Artist/Band.
\fBCDDB\fR \- CDDB, CDDB ID.
\fBCOMPOSER\fR \- Composer, Composed by.
\fBCONDUCTOR\fR \- Conductor, Conducted by.
\fBDATE\fR \- Date.
\fBENSEMBLE\fR \- Ensemble, Orquestra, Symphony.
\fBETREE\fR \- Etree, Etree DB. Non\-standard. See below.
\fBGENRE\fR \- Genre.
\fBIMAGE\fR \- Cover, Image.
\fBLOCATION\fR \- City, State, Country, Lieu, Location, Ville.
\fBMIXER\fR \- Mixer, Mixed by, Masterer, Mastered by.
\fBOPUS\fR \- Opus.
\fBPRODUCER\fR \- Producer, Recorded by, Taper, Taped By.
\fBPUBLISHER\fR \- Publisher, Label
\fBREMIXER\fR \- Remixer, Remixed by, Remasterer, Remastered by.
\fBSHNID\fR \- Shnid. Non\-standard. See below.
\fBSOURCEMEDIA\fR \- Media, SourceMedia, Source Media.
\fBType:\fR \- Extra data to append to ALBUM. See below.
\fBVENUE\fR \- Club, Event, Festival, Venue.
\fBYEAR\fR \- Year.
.fi

Notes:

* \fBALBUM\fR is constructed out of \fBDATE\fR, \fBLOCATION\fR, \fBVENUE\fR  if 
\fBAlbum\fR not explicitly supplied. See \fBDATE\fR, \fBETREE\fR, \fBSHNID\fR, 
\fBTYPE\fR below.

** \fBDATE\fR will be prepended to \fBALBUM\fR if no ALBUM supplied.

** \fBTYPE\fR if present: appends to end of ALBUM string: ' - [type]'. Normal 
values AUD, SBD, MTX, AUD 16/44.1, SBD Master 24/48, but can be anything. This 
goes before etree/shnid appends in ALBUM string.

** \fBETREE\fR if present: appends to end of ALBUM string: ' (etree [id])'

** \fBSHNID\fR if present: appends to end of ALBUM string: ' (shnid [id])'

* \fBBand:\fR will trigger \fBARTIST\fR only if in top block, before first 
empty line, since \fBBand:\fR can also be used to trigger \fBPERFORMERS\fR 
prefill if not in top block.

* \fBComposer:\fR, \fBConductor\fR, \fBEnsemble:\fR, \fBOpus:\fR are usually 
for classical recordings, but up to you.

* See \fB\-Xd\fR for date fixes, prefill only accepts YYYY\-MM\-DD formatting.

* \fBPRODUCER\fR is preferred over \fBMIXER\fR unless for example 1 person 
produced, taped, or otherwise created the recording, and another mixed or 
mastered it.

* \fBREMIXER\fR is if track is remixed, remastered. The person who did the
remix/remaster.

* \fBVENUE\fR will also be added to \fBLOCATION\fR if no \fBALBUM\fR set.

* \fBYEAR\fR is generated from \fBDATE\fR if no Year: supplied. 

Sample:
.nf\fB
Artist: The Band 
Album: Darkness in the Sunlight
Year: 1975
Cover: cover.jpg\fR
.fi

.B Both Methods

* Performers list must be preceded by a line starting with \fBBand:\fR, 
\fBLineup:\fR, \fBLine\-up:\fR, or \fBBand Lineup\fR, \fBBand Line\-up\fR, 
\fBMembers:\fR, or \fBBand Members\fR, \fBPerformers\fR, and must be followed by 
the band members list, with no empty lines between performers.

* Track numbers must start with either \fBX-X.\fR, \fBX-XX.\fR (for multidisc), 
\fBX.\fR or \fBXX.\fR where \fBX\fR is a number. The number of tracks listed 
must correspoond to the total number of actual track files present. If they do 
not match in counts, acxi will exit with an error.

* You can add a terminator to the Setlist/Tracks etc to stop creating and 
counting tracks. This helps when there are numbered comments, numbered per track 
notes, and so on, which could then trigger a track count mismatch exit error. 
Also makes it so you don't have to do anything to the info file other than add 
the terminator string. Not case sensitive. Supported:

One or more: \fB:^<>\fR followed by zero or one ES, ESL, ET, ETL, END, 
END\-TRACKS, END_TRACKS, END TRACKS, END\-SETLIST, END_SETLIST, END SETLIST, 
terminating in 1 or more \fB:^<>\fR.

Sample:
.nf\fB
Tracks:
 ...
09. Second to last Track
10. Last track

:::

Comments:
1. The first track was written by Jeff.
2. The second track was written by Frank.
 ...\fR
.fi

Other track prefill terminators might be \fB^END:\fR, \fB:END_TRACKS:\fR, 
\fB^_\fR, \fB<>\fR, and so on.

Must be only characters on line. \fB\-\fR and \fB=\fR not supported because 
syntax like \-\-\-\-\-\- is a very common part of info file track values.

Also used with \fB\-Xn\fR and \fB\-Xt\fR.

* Cover:/Image:, Genre:, Producer:/Taper:, CDDB, Etree, do not need to be in top 
block.

Should always be run in the flac folder with \fB\-s./\fR or unexpected results 
could occur.

Use together with \fB\-M\fR or \fB\-S\fR to prepopulate the \fBALBUM (if no 
Album field name, constructs from Date Location Venue strings),\fR \fBARTIST\fR, 
\fBALBUMARTIST\fR (Uses Artist unless field name AlbumArtist used), 
\fBPERFORMER\fR, \fBDATE\fR, \fBLOCATION\fR, \fBYEAR\fR, and track \fBTITLE\fR 
fields as well. 

Use the \fB\-\-test\fR option to make sure the data will prefill as expected
before actually creating the \fBauto.tag\fR file.

Samples: 

\fBacxi \-s./ \-ES\fR [single disc]

\fBacxi \-s./ \-EM d%\-\fR [multi disc, file name sample: d2\-track04.flac];

.TP
.B \-\-prefill\-file\fR, \fB\-\-pf {file name}\fR
.br
See \fB\-\-info\-file\fR.

.TP
.B \-\-prefill\-tag\fR, \fB\-\-pt\fR, \fB\-\-pft {tag-data}\fR
Uses same syntax as \fB\-\-tag\fR. One or more tags to populate auto.tag in 
prefill actions. See also configuration item \fBPREFILL_TAG\fR.

Sample: \fB\-\-prefill\-tag "GENRE%:Heavy Metal^^IMAGE%:cover.jpg"\fR

Value \fBUNSET\fR unsets \fBPREFILL_TAG\fR values, otherwise overrides those
values.

Supports same tags as \fB\-\-prefill\fR field names.s

.TP
.B \-\-remove\-images\fR,  \fB\-\-image\-remove\fR, \fB\-R\fR
Use with \fB\-\-autotag\fR or \fB\-\-image\fR. Will remove all embedded image data, 
and the associated padding, prior to tagging (and adding new image if 
applicable) audio file. Note that simply removing image data will leave the 
padding in place, which makes the file get bigger each time a new image is 
added. 

This is the full command required to fully restore a flac file size. Failure to 
use \fB\-\-dont\-use\-padding\fR leaves the file size unchanged.

\fBmetaflac \-\-remove \-\-block\-type=PICTURE,PADDING \-\-dont\-use\-padding 
file.flac\fR

.TP
.B \-\-remove\-padding\fR, \fB\-P\fR
Use with \fB\-\-autotag\fR and \fB\-\-tag\fR if you want to remove padding. My 
tests showed inconclusive results with this, and it slows down the tagging a 
lot, especially over network connections.

.TP
.B \-\-start {number}\fR
This option is ONLY used with the \fBauto.tag\fR file creation options: 
\fB\-M\fR, \fB\-S\fR and \fB\-C\fR.

For creating the track number tag, start \fBauto.tag\fR track numbering at a 
different value than default 1. This lets you handle cases where there was for 
example:

\fB00.intro.flac\fR

This will subtract 1 from track totals, so output is as expected, say for 0 
start, then 1-14 tracks, you will see 14/14 when your media player shows x/yy 
counts for track listings.

For values greater than 1, will add that number to the real found track totals, 
so that, for example, if first track is 03.flac, you will see 15/15 for track 
15.flac as you'd expect.

These are not normal circumstances, but they do happen, so now you can handle 
those. Check your work carefully, check the auto.tag file 

Note: some media players get confused by the track tag number 0, I beileve they 
are doing a type of if not test, and the 0 registers in some cases as not, so the 
player may show no track number, not the expected 0.

In general, use the \fB\-\-test\fR option to verify the results are what you 
expected before actually proceeding with this option for real.

.TP
.B \-\-tag\fR, \fB\-T {"TAG1%:tag value^^TAG2%:tag value"}\fR
Modify one or more tags in a single recording or group of recordings. FLAC only, 
use standard FLAC tag values for best results. Separate \fBTAG\fR and \fBtag 
value\fR with \fB%:\fR, and separate tag/value sets with \fB^^\fR. This lets you 
retag entire blocks of artist/recordings at once if you only want to modify (or 
create) one or more FLAC tags.

Removes all existing tags of that type before updating since FLAC just adds the 
new tag to the already existing set of tags by default.

Sample: \fBacxi \-s ./ \-\-tag "GENRE%:Heavy Metal^^ARTIST%:Black Sabbath"\fR

If tag value is \fBUNSET\fR it will just remove that tag and its contents.

Sample: \fBacxi \-s ./ \-\-tag "COMMENT%:UNSET^^ARTIST%:Black Sabbath"\fR

.TP
.B \-\-taglist\fR, \fB\-L [acfisw]\fR
Use to create tag data output to screen. Generates a list of the raw tags per 
file in each directory of FLACS. To create the info.txt or taglist.tag file(s) 
per FLAC directory, add \fBw\fR.

* \fBnothing\fR \- same as \fBf\fR. Create full tag list output.

* \fBa\fR \- Switch output to tag key/value \fB%:\fR separator from \fB=\fR, and 
change output file from \fBtaglist.tag\fR to \fBauto.tag\fR. If \fBc\fR and 
\fBf\fR not used, defaults to \fBc\fR. This allows you to use the resulting file 
as a source for \fB\-\-autotag\fR. 

* \fBc\fR \- Generate condensed taglist data. Useful if each file has mostly the 
same tags, with only a few differing. UNSETs tag names after each block of files 
that used that tag unless that tag's value is replaced by another value or it's 
the last file.

* \fBf\fR \- Generate full per audio file taglist data. This is all the tags 
found per audio file in the order the files occur. This is the default action. 
Adds value \fBTAGBLOCK\fR to \fBUNIQUE\fR at top of file so each file is tagged 
only with the tags in its block, no cascade of tags occurs.

* \fBi\fR \- Generate info file data. Disables taglist unless a/c/f used.

* \fBs\fR \- Skip the file exists tests. Can't be used with w. 

* \fBw\fR \- Write changes to file(s). Only writes if info.txt and/or 
taglist.tag files are not in directory.

Sample (print condensed taglist file to screen):

.EX
\fBacxi \-s ./ \-Lc\fR
.EE

Sample (creates taglist.tag file(s), no tag data printed to screen):

.EX
\fBacxi \-s ./ \-\-taglist w\fR
.EE

Sample (creates taglist condensed and info file data, prints to screen, and to
file to store this data):

.EX
\fBacxi \-s ./ \-Lci 2>&1 | tee taglist\-data.txt\fR
.EE

If you want to check many directory tag sets but some have \fBinfo.txt\fR or 
\fBtaglist.tag\fR and some don't, use \fBs\fR, which will skip the file exist 
tests.

To change on a one time basis the file names to be created or tested for:

\fB\-\-info\-file foo.txt\fR / \fB\-\-taglist\-file foo.tag\fR

.TP
.B \-\-taglist\-file\fR, \fB\-\-tlf\fR, \fB\-\-tf\fR {file}
An alternate file name to use for \fB\-\-taglist\fR. Note that file MUST have a 
*.tag extension, and should not be anything other than ASCII or UTF8, otherwise 
you will get ungood results.

.TP
.B \-\-unique\fR {comma separated tags}
The comma separated list of tag names will be used to set those tags to be used 
only 1x per file when found in \fBauto.tag\fR file, and unset after. You can 
also set this list manually in the \fBauto.tag\fR file top special field 
\fBUNIQUE%:\fR. This will make those tags work in a similar way to \fBVERSION\fR 
or \fBPART\fR or \fBTITLE\fR. \fBTAGBLOCK\fR value will treat each set of 
tags before the \fBFILE%:\fR item as applying only to that single file.

You need to add these tags in \fBauto.tag\fR right before the file tag block 
that will use that tag. Note that \fBUNIQUE\fR tags will override any global or 
tag block use of that tag name.

DO NOT USE IF TAG APPLIES TO MORE THAN ONE CONSECUTIVE FILE! In that case, set 
the tag before the block of files, and it will apply to all following files 
until the next new value. If it applies only to a block, and is not replaced by 
another value, use value \fBUNSET\fR for \fBTAGNAME\fR after the last file that 
uses it, unless that file is also the last file in the list.

\fB\-La\fR/\fB\-Lc\fR UNSETs the tag at the end of each block of tags 
automatically.

\fB\-Lf\fR/\fB\-Laf\fR add value \fBTAGBLOCK\fR to \fBUNIQUE\fR automatically.

When used with \fB\-C\fR, \fB\-M\fR, or \fB\-S\fR will set the \fBUNIQUE\fR 
value in the generated \fBauto.tag\fR file.

Sample: with command line:
.br
\fBacxi \-s ./ -A \-\-unique COMPOSER,ARRANGER\fR
.br
Sample: in \fBauto.tag\fR file:
\fBUNIQUE%:COMPOSER\,ARRANGER\fR

.SH ANALYZE/CHECKSUM OPTIONS
Create checksum files (ffp/md5), verify checksums, analyze sets of files, check 
collection for duplicate ffps.

.TP
.B \-\-analyze\fR, \fB\-Z\fR
Similar to \fB\-Xq\fR, except creates per file/directory reports with screen 
output. Shows input tye file quality (sample bit size, sampling rate, and 
channels), size, duration, kb/s, and also per directory summaries of those 
values. In directory summary, if more than one input file quality type found in 
directory, will print out each type found, which can be useful to see if 
different sampling rates or sample bit sizes were used.

To write to a file, use something like this:
.EX
\fBacxi -s./ \-\-analyze 2&>1 | tee analyze.txt\fR
.EE
The tee will allow the output to also scroll on screen while it runs, which is
helpful in many cases. Otherwise just redirect output to file directly.

\fB\-v 0\fR turns off per file reports, and shows only per directory summary; 
\fB\-v 2\fR wraps per file data to key: value pair lines, adds ffp signature 
(flac only); \fB\-v 3\fR adds raw non rounded seconds and file size in bytes to 
all size / time results.

Note that default for flac is metaflac, unless you use \fB\-\-ffprobe\fR, which 
does not have hashes. Use metaflac for flac, it's about 25x or more faster than 
ffprobe!!

To verify \fB\-Xq\fR, use \fB\-Xv\fR instead, which will add an FFP verification 
report item to the analysis block.

.TP
.B \-\-checksum\fR, \fB\-K\fR
Create \fB.ffp\fR and \fB.md5\fR checksum files in your source directory. 
Checksum files are only created inside directories where flac files are found. 
Use \fB\-\-checksum\-delete\fR if you also want to delete existing checksum 
files before creating new ones. Only flac input type is supported.

This will not create md5 sums for for files in directories that do not contain 
flac files, because that creates a very complicated logical puzzle which is hard 
to accurately or reliably resolve in code.

Do not use together with other cleaning/syncing options. Can be used with 
\fB\-A\fR.

.TP
.B \-\-checksum\-delete\fR, \fB\-D\fR
Will first delete all \fB.md5\fR, \fB.md5.txt\fR, \fB.ffp\fR, \fB.ffp.txt\fR,  
\fB.st5\fR, and \fBshntool.txt\fR files before creating new checksum files. 
\fB.st5\fR and \fBshntool.txt\fR were often created by shntool. Also removes 
\fBrobots.txt\fR files, which sometimes were added by some downloaders in the 
past. 

Note that some audio processing tools add \fB.txt\fR to the checksum file name, 
which creates undesirable outcomes since some tools that use \fB.ffp\fR or 
\fB.md5\fR files don't recognize the files if they have the \fB.txt\fR extension 
added on.

I can think of very few reasons to want to preserve \fB.ffp\fR or \fB.md5\fR 
files, since they should in general reflect what the actual files you have are.

Do not use together with other cleaning/syncing options. Can be used with 
\fB\-A\fR.

.TP
.B \-\-checksum\-ffps\fR, \fB\-\-ffps\fR
Prints checksums to screen, disables md5 generation and output. Useful for 
generating large lists of ffps for a collection.

Similar to: \fBacxi \-K \-\-no\-md5 \-\-test\fR

Sample (prints to screen, redirects stderr to stdout, prints to file):
.EX
\fBacxi \-s ./ \-\-ffps 2>&1 | tee ffps.txt\fB
.EE

.TP
.B \-\-checksum\-verify\fR, \fB\-V\fR
Will read existing .md5 files and compare md5 hash of files listed in the md5 
file with the actual checksums of those files. Also will verify FLAC integrity 
(this is pretty slow, so be patient).

Note that when reading md5s, it does not matter if they are windows or *nix path 
styles (/ or \/), it translates them to the one on your system. It also ignores 
line endings, which makes reading windows generated md5 files on *nix systems a 
breeze.

See also \fB\-Xv\fR for adding FFP verification item to that block.

.TP
.B \-\-duplicates\fR, \fB\-\-dupes\fR
Check your collection for duplicated flac files or releases, helpful to find 
repeated items in your collection. Note that in cases of only 1 file matching, 
it's in theory possible for that to be a random coincidence, so always confirm 
before deleting anything!! But it's pretty rare for an ffp hash to be 
duplicated.

For larger directories/collections, use 

\fBacxi -s./ \-\-dupes 2>&1 | tee duplicates.txt\fR

The tee will allow the output to also scroll on screen while it runs, which is
helpful to see what's going on. Otherwise just redirect output to file directly.

.TP
.B \-\-no\-ffp\fR
Skips FLAC ffp checks and generation on \fB\-\-checksum\fR, 
\fB\-\-checksum\-delete\fR, and \fB\-\-checksum\-verify\fR. Useful if you have 
already verified or created ffp/flac data and only want to check md5 sums.

.TP
.B \-\-no\-md5\fR
Skips md5 checks and generation on \fB\-\-checksum\fR, 
\fB\-\-checksum\-delete\fR, and \fB\-\-checksum\-verify\fR. Useful if you only 
want to check / create ffp data, which is much faster to generate than md5 
checksums.

.TP
.B \-\-z\-min\-size {number}\fR
Override default value for \fB\-\-analyze\fR min lossless file size alert.
Number is integer KiB, 0\-xxx. 0 disables this test. Can be set in config file,
see config section.

.TP
.B \-\-z\-min\-time {number}\fR
Override default value for \fB\-\-analyze\fR min file duration alert. Number is 
integer seconds, 0\-xxx. 0 disables this test. Can be set in config file, see 
config section.

.SH MISCELLANEOUS OPTIONS

.TP
.B \-\-aggregate, \fB\-G\fR [filename|extension]\fR
Collect all the \fBauto.tag\fR files in a source directory and send to a target 
directory. Useful to collect data for a large collection. You can supply a list 
of comma separated items: jpg,info.txt,myart.png

Creates the directories the files were found in in the destination directory.

If no extra argument is supplied, it will default to collecting all the 
\fBauto.tag\fR files in the source directory.

Sample 1 (collects all auto.tag files): 
.EX
\fBacxi \-\-aggregate \-s my\-music -d music\-data\fR
.EE
Sample 2 (collects all supplied filename): 
.EX
\fBacxi \-\-aggregate info.txt \-s my\-music -d music\-data\fR
.EE
Sample 3 (collects all files of type jpg): 
.EX
\fBacxi \-\-aggregate jpg \-s my\-music -d music\-data\fR
.EE
Sample 4 (collects multiple values):
.EX
\fBacxi \-\-aggregate jpg,info.txt,png \-s my\-music -d music\-data\fR
.EE

.TP
.B \-\-config\fR, \fB\-\-configuration\fR
Show active configuration values, by file, and exit.

.TP
.B \-\-help\fR, \fB\-h\fR
The help / options menu.

.TP
.B \-\-no\-ssl\fR
Disable SSL strict certificate checks for \fB\-U\fR. 

Sample: \fB\acxi -U3 \-\-no\-ssl\fR

This can be useful because github doesn't usually allow connections without 
strict SSL checks, but legacy systems often have expired SSL certificates. 

.TP
.B \-\-update\fR, \fB\-U [3]\fR
Self updater, will update acxi and its man page. Non GNU/LInux will probably 
require changing the default values, which are set in \fBUSER VARIABLES\fR for 
curl, acxi and man page acxi.1. Requires \fBcurl\fR.

If you add \fB3\fR (\fB\-U 3\fR), \fBacxi\fR will update from \fIsmxi.org\fR 
server instead (that version is updated at least 1x per day, more during active 
development). Avoid this unless you have been asked to do it, or if you are 
running acxi on a legacy server with expired SSL certificates and need to use 
\fB\-\-no\-ssl\fR (\fB\-U 3 \-\-no\-ssl\fR).

.TP
.B \-\-version\fR
Show acxi version.

.SH DEBUG/OUTPUT CONTROL OPTIONS
These options allow you to modify the output, or to test actions before doing 
them for real.

.TP
.B \-\-dbg {1\-xx}[,1\-xx]\fR
Activate specialized debugger outputs. Accepts comma separated list of integers 
to trigger > 1 debugger action.

See stable branch \fIdocs/acxi\-values.txt\fR for more granular and current 
explanations.

\fB1\fR \- Primary raw data).

\fB2\fR \- Secondary raw data from text files.

\fB3\fR \- Post processed secondary data.

\fB4\fR \- File/Directory data during processing.

\fB5\fR \- Command strings being run.

\fB6\fR \- Generated data by subs, primary.

\fB7\fR, \fB8\fR \- Data from specific tools and utilities.

\fB20+\fR - Advanced data and debuggers.

.TP
.B \-\-dry\-run\fR, \fB\-\-dry\fR, \fB\-\-test\fR
.br
See \fB\-\-test\fR.

.TP
.B \-\-quiet\fR, \fB\-\-silent\fR
Turns off most screen output, except for error messages. Same as \fB\-v 0\fR.
Not used for all features since it makes no sense to turn off screen output for
features that require screen output, like \fB\-Z\fR.

.TP
.B \-\-test\fR, \fB\-\-dry\fR, \fB\-\-dry\-run\fR
Test your configurations, copy, sync, checksum, and tagging actions without 
actually doing the operations. 

.TP
.B \-\-verbosity\fR, \fB\-v {0-3}\fR
Dynamically set . Helps for debugging certain types of issues where you might 
advanced highly verbose debugging information. 

\fB0\fR \- shuts off most output except errors. Same as \fB\-\-quiet\fR. Not 
useful or used for all features.

\fB1\fR \- basic single line output.

\fB2\fR \- more verbose output. 

\fB3\fR \- full output, incuding all conversion tool output.

For other technical data, see \fB\-\-dbg\fR, but not unless you know why you are 
doing it. 

.SH CONFIGURATION FILE
You can see by running \fBacxi \-h\fR the configuration file locations.

acxi will read its configuration/initialization files in the following order.

.TP
.B STANDARD DETECTION
\fB/etc/acxi.conf\fR contains the default configurations. Also checks 
\fB/etc/acxi.conf.d/acxi.conf\fR as global override for \fB/etc/acxi.conf\fR  
config file. Useful in cases if distros package acxi to override any defaults.

These can be overridden by user configurations found in one of the following 
locations, in this order of priority: \fB$XDG_CONFIG_HOME/acxi.conf\fR, 
\fB$HOME/.config/acxi.conf\fR, and, as last default, \fB$HOME/.acxi.conf\fR, i.e.:

\fB$XDG_CONFIG_HOME/acxi.conf\fR > \fB$HOME/.config/acxi.conf\fR >
\fB$HOME/.acxi.conf\fR > \fB/etc/acxi.conf.d/acxi.conf\fR > \fB/etc/acxi.conf\fR

.TP
.B MANUALLY SET
\fB$CONFIG_DIRECTORY\fR \- Sample: 
\fB$CONFIG_DIRECTORY='/path/to/configuration/directory'\fR

NOTE: only use this method if you are running Windows, or any OS without 
\fB$HOME\fR or \fB$XDG_CONFIG_HOME\fR environmental variables, or if you want 
the configuration file to be located somewhere else. 

This value must be set on top of acxi in the \fBUSER MODIFIABLE VALUES\fR 
section because that is what it will use to locate the configuration file. acxi 
will look for acxi.conf inside that directory. This path value will 
override/ignore all other configuration files.

.SH CONFIGURATION OPTIONS
The following corresponds to the \fBUSER MODIFIABLE VALUES\fR section in the top 
comment header of acxi.

Sample contents of a configuration file:
.nf
\fBDESTINATION_DIRECTORY=/home/fred/music/opus
SOURCE_DIRECTORY=/home/fred/music/flac
COPY_TYPES=gif,jpg,jpeg,png,txt
OUTPUT_TYPE=opus
QUALITY_OPUS=160
EXCLUDE=/doc/^^/docs/^^/images/^^/pictures/^^/artwork/^^/photos/^^\fR
.fi

.TP
.B APPLICATION PATHS
The following set your system path for the required applications:

\fBCOMMAND_FFMPEG\fR \- Sample: \fBCOMMAND_FFMPEG=/usr/bin/ffmpeg\fR (default 
path)

\fBCOMMAND_FFPROBE\fR \- Sample: \fBCOMMAND_FFPROBE=/usr/bin/ffprobe\fR (default 
path)

\fBCOMMAND_FLAC\fR \- Sample: \fBCOMMAND_FLAC=/usr/bin/flac\fR (default path)

\fBCOMMAND_LAME\fR \- Sample: \fBCOMMAND_LAME=/usr/bin/lame\fR (default path)

\fBCOMMAND_METAFLAC\fR \- Sample: \fBCOMMAND_METAFLAC=/usr/bin/metaflac\fR 

\fBCOMMAND_OGG\fR \- Sample: \fBCOMMAND_OGG=/usr/bin/oggenc\fR (default path)

\fBCOMMAND_OPUS\fR \- Sample: \fBCOMMAND_OPUS=/usr/bin/opusenc\fR (default path)

.TP
.B SOURCE/DESTINATION/CONFIGURATION DIRECTORIES
NOTE: \fBDESTINATION_DIRECTORY\fR cannot be the same as \fBSOURCE_DIRECTORY\fR.

\fBCLEAN\fR \- Sample: \fBCLEAN=true\fR Switches on/off \fB\-\-clean sync\fR to 
apply cleaning action to your destination directories. Accepted values: 
\fB[enable|on|true|yes]\fR or \fB[disable|off|false|no]\fR. Default is false. 

\fBDESTINATION_DIRECTORY\fR \- Sample: 
\fBDESTINATION_DIRECTORY=/home/fred/music/ogg\fR

This is the processed compressed music files, ie, ogg, opus, or mp3. Destination 
cannot be the same as Source directory, although it can be inside of the source 
directory.

\fBSOURCE_DIRECTORY\fR \- Sample: \fBSOURCE_DIRECTORY=/home/fred/music\fR 

This the original, working, like flac, wav, etc.

.TP
.B EXCLUDE LISTS/FILES
\fBDOT\fR \- Disables default behavior of skipping all files starting with a 
\fB.\fR. Takes values true or false. Note that false is the acxi default so there's 
no point in using that.

\fBEXCLUDE\fR \- Sample (if list): \fBEXCLUDE=artwork^^Daisy Queen^^Bon Jovi\fR

Sample (if exclude file): 
\fBEXCLUDE=/home/me/music/excludes/acxi-excludes-phone.txt\fR

Excludes these matches from destination directory in sync or clean operations.

\fBEXCLUDE_BASE\fR \- Sample: \fBEXCLUDE_BASE=massive-exclude-list\fR 

This is the part of the file name minus the .txt that will be matched to see if 
it's an exclude list or an exclude file. Default: \fBacxi-excludes\fR

This lets you use multiple exclude files, as long as they all contain the value
found in \fBEXCLUDE_BASE\fR acxi will know it's an exclude file, not a list.

.TP
.B INPUT/OUTPUT
The following are NOT case sensitive,ie flac/FLAC, txt/TXT will be found. 
INPUT_TYPE and OUTPUT_TYPE will be forced to lower case internally.

Changing quality levels will not redo existing files.

\fBCODEC_AAC\fR \- Sample (default value): \fBCODEC_AAC=libfdk_aac\fR 

\fBCOPY_TYPES\fR \- Sample: \fBCOPY_TYPES=doc,docx,bmp,jpg,jpeg\fR Use this to 
override the default file types acxi will sync. Set to 'none', if you only want 
to sync the music files, not copy over images, text files, etc.

\fBDITHER\fR \- Sample (default value): \fBDITHER=shibata\fR See 
\fB\-\-dither\fR for values.

\fBINPUT_TYPE\fR \- Sample: \fBINPUT_TYPE=flac\fR 

\fBOUTPUT_TYPE\fR \- Sample: \fBOUTPUT_TYPE=mp3\fR 

\fBQUALITY_AAC\fR \- Sample: \fBQUALITY_AAC=320\fR Supported values: 10 to 500. 
500 is the largest file size / highest quality. Applies to aac and m4a.

\fBQUALITY_FLAC\fR \- Sample: \fBQUALITY_FLAC=5\fR Supported values: 0\-8. 0 is 
the largest file size / fastest to run. 5 to 8 shows only a tiny decrease in 
file size but a large increase in time to process, so 4 is a good balance in 
general.

\fBQUALITY_MP3\fR \- Sample: \fBQUALITY_MP3=2\fR Supported values: 0\-9.999. 0 
is the largest file size / highest quality. Decimals OK.

\fBQUALITY_OGG\fR \- Sample: \fBQUALITY_OGG=8.25\fR Supported values: \-1 to 
10. 10 is the largest file size / highest quality. Decimals OK.

\fBQUALITY_OPUS\fR \- Sample: \fBQUALITY_OPUS=256\fR Supported values: 6\-256. 
256 is the largest file size / highest quality / best bitrate.

.TP
.B ANALYZE
These two values allow you to customize default -Z ALERT warnings about possible
incorrect file size and time duration values. Useful for finding accidentally
corrupted or otherwise incorrect files.

\fBZ_MIN_SIZE\fR \- Sample: \fBZ_MIN_SIZE=900\fR Minimum size (in KiB) in 
integers of lossless file. Not used for lossy files. Set to 0 to disable. See\fB 
\-\-z\-min\-size\fR

\fBZ_MIN_TIME\fR \- Sample: \fBZ_MIN_TIME=8\fR Minimum time/duration in integer 
seconds of audio file. Set to 0 to disable. See\fB \-\-z\-min\-time\fR

.TP
.B AUTO\-TAGGING
These only apply to the \fB\-\-autotag\fR option, and set a different name for 
the default auto.tag filename. The filename must be unique and never occur in 
any other context in your music collection files.

\fBAUTOTAG_FILE\fR \- Sample: \fBAUTOTAG_FILE=autotags.tag\fR. Test with 
\fB\-\-autotag\-file {file}\fR.

\fBauto.tag\fR \- The filename to be used to autotag. Default is \fBauto.tag\fR. 
Filename must be unique, and must not be found anywhere else in your collection. 
Do not change unless you have a very good reason to.

\fBINFO_FILE\fR \- Sample (default value): \fBINFO_FILE=info.txt\fR 

\fBinfo.txt\fR \- The filename in the flac directory being processed that will
be used to populate the \fBauto.tag\fR fields.

\fBINFO_RATING\fR \- Sample (default value): \fBINFO_RATING=4\fR. See 
\fB\-\-info\-rating\fR. Used with \fB\-X q\fR. Must be greater than 1.

\fBPREFILL_TAG\fR \- Same syntax as \fB\-\-tag\fR. Remember to clear this if you
don't want these tags to be always used in prefill actions. 

Sample: \fBPREFILL_TAG=GENRE%:Heavy Metal^^IMAGE%:cover.jpg\fR 

\fBTAGLIST_FILE\fR \- Sample: \fBTAGLIST_FILE=taglists.tag\fR 

\fBtaglist.tag\fR \- The filename to be used to by \fB\-\-taglist\fR. Default is 
\fBtaglist.tag\fR

Filename must be unique, and must not be found anywhere else in your collection. 
Do not change unless you have a very good reason to.

.TP
.B CHECKSUMS
These only apply to the \fB\-\-checksum\fR option, and set a different name than 
the default file names used in the top section of acxi. Note that the names 
should not include an extension, since that is added on automatically.

\fBFFP_FILE\fR \- Sample: \fBFPP_FILE=fingerprint\fR This is the name of the 
generated .ffp file, not including the .ffp extension, you want your flac ffp 
files to have. 

\fBMD5_FILE\fR \- Sample: \fBMD5_FILE=checksum\fR This is the name of the 
generated .md5 file, not including the .md5 extension, you want your md5 
checksum files to have.

.TP
.B VERBOSITY LEVELS
You can change \fBVERBOSITY\fR either at the top of the \fBacxi\fR file itself, 
or in the configuration file, by setting the verbosity/debugging level to what 
you want. Deprecated: \fBLOG_LEVEL\fR.

Sample: \fBVERBOSITY=3\fR 

\fB0\fR \- quiet/silent \- no output at all (except for errors).

\fB1\fR \- basic \- single line per operation. This is the default, so you don't 
need to change it.

\fB2\fR \- verbose \- but without the actual conversion data from codecs

\fB3\fR \- full \- all available information. Note: with \fB\-F\fR / 
\fB\-\-fork\fR conversion output may be ordered somewhat randomly since it shows 
each thread's results as it completes as well as when it started.

.TP
.B ADVANCED
The following are advanced options which should only be used if you know what 
you are doing:

\fBDONT_USE_NLINK\fR \- Sample: \fBDONT_USE_NLINK=0\fR 
This sets \fBFile::Find::dont_use_nlink to \fB0\fR or \fB1\fR. \fB1\fR is 
default. Generally you should be using \fB1\fR, but in certain cases \fB0\fR may 
be faster. Test using the \fB\-\-nlink\fR option to disable nlink, and see that 
option for more information.

\fBFORK\fR \- Sample: \fBFORK=4\fR 
This uses Perl's \fBParallel::ForkManager\fR and accepts values of 0 or more. 
Note that 0 will not create a fork. See \fB\-\-fork\fR for details. Using this 
will speed up your syncing a lot if you have more than a 1 core CPU.

.TP
.B SELF UPDATER
These are only for the \fB\-U\fR self updater feature. The path defaults must be 
changed for non\-GNU/Linux systems in most cases.

\fBCOMMAND_CURL\fR \- Sample: \fBCOMMAND_CURL=/usr/local/bin\fR

\fBMAN_DIRECTORY\fR \- Sample: \fBMAN_DIRECTORY=/usr/share/man/man1\fR This is 
the directory the man page is in.

\fBSELF_DIRECTORY\fR \- Sample: \fBSELF_DIRECTORY=/usr/bin\fR This is the 
directory that \fBacxi\fR is in.

.SH BUGS
Please report bugs using the following resources.
.TP
.B Issue Report
File an issue report:
.I https://github.com/smxi/acxi/issues
.TP
.B Forums
Post on acxi forums:
.I https://techpatterns.com/forums/about1491.html
.TP
.B IRC
You can also visit
.I irc.oftc.net
or
.I irc.libera.chat
\fRchannel:\fI #smxi\fR to post issues. Libera is probably best for acxi issues.

.SH HOMEPAGE
.I https://github.com/smxi/acxi

.SH AUTHOR AND CONTRIBUTORS TO CODE
.\" don't change this line until new acxi out for a while, used for -U test
acxi is a fork and full rewrite of flac2ogg.pl.

Copyright (c) Harald Hope, 2010\-2023

Initial forking logic: prupert. 2019-07

Initial MP3 tagging logic: Odd Eivind Ebbesen \- \fIwww.oddware.net\fR \- 
<oddebb at gmail dot com>

Copyright (c) (flac2ogg.pl) 2004 \- Jason L. Buberel \- jason@buberel.org

Copyright (c) (flac2ogg.pl) 2007 \- Evan Boggs \- etboggs@indiana.edu

Thanks for trying acxi out, I hope it's useful to you.

.\" EOF
